package view;

import dao.BoletosDAO;
import domain.Boletos;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CadBoletos extends javax.swing.JInternalFrame {

    BoletosDAO bdao;
    Boletos boletos;

    private void limpaCampos() {
        txtBeneficiario.setText("");
        txtDataVenc.setText("");
        txtStatus.setText("NÃO");
        txtValor.setText("");
    }

    //habilita campos
    private void habilitaCampos() {
        txtBeneficiario.enable();
        txtDataVenc.enable();
        txtValor.enable();
    }

    //desabilita botões
    private void desabilitaCampos() {
        btnSalvar.setVisible(false);
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);

        txtBeneficiario.disable();
        txtDataVenc.disable();
        txtValor.disable();
    }

    // carrega tabela principal
    private void carregaTabela(String status_pgto) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("BENEFICIÁRIO");
        modelo.addColumn("VALOR");
        modelo.addColumn("DATA VENCIMENTO");
        modelo.addColumn("Status PGTO");

        bdao = new BoletosDAO();
        for (Boletos b : bdao.listarBoletosNaoPagos("NÃO")) {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = formato.format(b.getDtVenc());

            modelo.addRow(new Object[]{b.getCodigo(), b.getBeneficiario(), 
                Double.toString(b.getValor()).replace(".", ","), dataFormatada, b.getStatus()});
        }

        tbBoletos.setModel(modelo);
    }

    /**
     * Creates new form CadBoletos
     */
    public CadBoletos() {
        initComponents();

        this.carregaTabela("");
        this.desabilitaCampos();

        txtStatus.setText("NÃO");

        lbCodigo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPesquisa = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBoletos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDataVenc = new javax.swing.JFormattedTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        txtBeneficiario = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        lbCodigo = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();

        setClosable(true);
        setForeground(new java.awt.Color(0, 0, 0));
        setTitle("Cadastro de Boletos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbBoletos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbBoletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbBoletosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbBoletos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 600, 490));

        jLabel1.setText("Beneficiário:*");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setText("Valor:*");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Data do Vencimento:*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        try {
            txtDataVenc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtDataVenc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));

        btnNovo.setBackground(new java.awt.Color(51, 51, 51));
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, 40));

        btnSalvar.setBackground(new java.awt.Color(51, 51, 51));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 80, 40));

        btnEditar.setBackground(new java.awt.Color(51, 51, 51));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 80, 40));

        jLabel5.setText("Status do Pgto(Boleto Pago?):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, -1));
        getContentPane().add(txtBeneficiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, -1));

        btnExcluir.setBackground(new java.awt.Color(51, 51, 51));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 80, 40));

        lbCodigo.setText("codigo");
        getContentPane().add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 80, -1));

        txtStatus.setEditable(false);
        txtStatus.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));

        setBounds(0, 0, 968, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtBeneficiario.getText().isEmpty() || txtDataVenc.getText().isEmpty()
                || txtValor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os todos campos com (*)",
                    "Atenção", JOptionPane.ERROR_MESSAGE);
        } else {
            boletos = new Boletos();
            bdao = new BoletosDAO();

            //formata data para salvar no banco
            String dia = txtDataVenc.getText().substring(0, 2);
            String mes = txtDataVenc.getText().substring(3, 5);
            String ano = txtDataVenc.getText().substring(6);

            String dataSalva = ano + "-" + mes + "-" + dia;
            Date dataVenc = new Date();
            SimpleDateFormat dtFormatada = new SimpleDateFormat("yyyy-MM-dd");

            try {
                dataVenc = dtFormatada.parse(dataSalva);
            } catch (ParseException ex) {
                Logger.getLogger(CadBoletos.class.getName()).log(Level.SEVERE, null, ex);
            }

            boletos.setBeneficiario(txtBeneficiario.getText().toUpperCase());
            boletos.setValor(Double.parseDouble(txtValor.getText().replace(",", ".")));
            boletos.setStatus(txtStatus.getText());
            boletos.setDtVenc(dataVenc);

            bdao.merge(boletos);

            this.desabilitaCampos();
            btnSalvar.setVisible(false);
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            this.limpaCampos();
            this.carregaTabela("NÃO");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tbBoletosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBoletosMousePressed
        this.habilitaCampos();

        btnSalvar.setVisible(false);
        btnEditar.setVisible(true);
        btnExcluir.setVisible(true);

        lbCodigo.setText(tbBoletos.getModel().getValueAt(tbBoletos.getSelectedRow(), 0) + "");
        txtBeneficiario.setText(tbBoletos.getModel().getValueAt(tbBoletos.getSelectedRow(), 1) + "");
        txtValor.setText(tbBoletos.getModel().getValueAt(tbBoletos.getSelectedRow(), 2) + "");
        txtDataVenc.setText(tbBoletos.getModel().getValueAt(tbBoletos.getSelectedRow(), 3) + "");
        txtStatus.setText(tbBoletos.getModel().getValueAt(tbBoletos.getSelectedRow(), 4) + "");

    }//GEN-LAST:event_tbBoletosMousePressed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtStatus.getText().equals("NÃO")) {
            txtStatus.setText("SIM");
        } else {
            txtStatus.setText("NÃO");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtBeneficiario.getText().isEmpty() || txtDataVenc.getText().isEmpty()
                || txtValor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os todos campos com (*)",
                    "Atenção", JOptionPane.ERROR_MESSAGE);
        } else {
            boletos = new Boletos();
            bdao = new BoletosDAO();
            //formata data para salvar no banco
            String dia = txtDataVenc.getText().substring(0, 2);
            String mes = txtDataVenc.getText().substring(3, 5);
            String ano = txtDataVenc.getText().substring(6);

            String dataSalva = ano + "-" + mes + "-" + dia;
            Date dataVenc = new Date();
            SimpleDateFormat dtFormatada = new SimpleDateFormat("yyyy-MM-dd");

            try {
                dataVenc = dtFormatada.parse(dataSalva);
            } catch (ParseException ex) {
                Logger.getLogger(CadBoletos.class.getName()).log(Level.SEVERE, null, ex);
            }

            boletos = bdao.buscarCodigo(Long.parseLong(lbCodigo.getText()));
            boletos.setBeneficiario(txtBeneficiario.getText());
            boletos.setValor(Double.parseDouble(txtValor.getText().replace(",", ".")));
            boletos.setDtVenc(dataVenc);
            boletos.setStatus(txtStatus.getText());

            bdao.merge(boletos);

            this.desabilitaCampos();
            btnNovo.setVisible(true);
            btnEditar.setVisible(false);
            btnExcluir.setVisible(false);
            JOptionPane.showMessageDialog(null, "Editado com sucesso!");
            this.limpaCampos();
            this.carregaTabela("NÃO");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        boletos = new Boletos();
        bdao = new BoletosDAO();

        boletos = bdao.buscarCodigo(Long.parseLong(lbCodigo.getText()));
        bdao.excluir(boletos);

        this.desabilitaCampos();
        btnNovo.setVisible(true);
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
        JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
        this.limpaCampos();
        this.carregaTabela("NÃO");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtBeneficiario.requestFocus();
        this.habilitaCampos();
        this.limpaCampos();
        btnSalvar.setVisible(true);
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
    }//GEN-LAST:event_btnNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup grupoPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JTable tbBoletos;
    private javax.swing.JTextField txtBeneficiario;
    private javax.swing.JFormattedTextField txtDataVenc;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
